name: healthcare_mania_2024
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  intl: ^0.19.0
  flutter_charts: ^0.5.2
  pod: ^0.18.0
  flutter_launcher_icons: ^0.14.2

#  追加
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/humedicalicon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true